#!/usr/bin/env bash

KEYRING_FILE_NAME=newrelic-infra-keyring.gpg
TRUSTED_GPG_D_KEYRING=/etc/apt/trusted.gpg.d/${KEYRING_FILE_NAME}
USR_SHARE_KEYRING=/usr/share/keyrings/${KEYRING_FILE_NAME}

rm "${USR_SHARE_KEYRING}" 
rm "${USR_SHARE_KEYRING}~" 
rm "${TRUSTED_GPG_D_KEYRING}" 

exit 0
